Pages/DeleteItems.cshtml.cs
using System.Collections.Generic;
using HtmxDemo.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace HtmxDemo.Pages
{
    public class DeleteItemsModel : PageModel
    {
        private readonly Database _database;

        public List<Customer> Customers { get; set; }

        public DeleteItemsModel(Database database)
        {
            _database = database;
        }

        public void OnGet()
        {
            Customers = _database.Customers;
        }

        public IActionResult OnPostDelete(int id)
        {
            _database.Customers.RemoveAll(customer => customer.Id == id);

            return new ContentResult();
        }
    }
}

Pages/DeleteWithPartialRefresh.cshtml.cs
using System.Collections.Generic;
using HtmxDemo.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace HtmxDemo.Pages
{
    public class DeleteWithPartialRefreshModel : PageModel
    {
        private readonly Database _database;
        
        public List<Customer> Customers { get; set; }

        public DeleteWithPartialRefreshModel(Database database)
        {
            _database = database;
        }
        
        public void OnGet()
        {
            Customers = _database.Customers;
        }
        
        public IActionResult OnPostDelete(int id)
        {
            _database.Customers.RemoveAll(customer => customer.Id == id);

            return Partial("_CustomerList", _database.Customers);
        }
    }
}

Pages/DeleteWithRefresh.cshtml.cs
using System.Collections.Generic;
using HtmxDemo.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Primitives;

namespace HtmxDemo.Pages
{
    public class DeleteWithRefreshModel : PageModel
    {
        private readonly Database _database;

        public List<Customer> Customers { get; set; }
        
        public DeleteWithRefreshModel(Database database)
        {
            _database = database;
        }
        
        public void OnGet()
        {
            Customers = _database.Customers;    
        }
        
        public IActionResult OnPostDelete(int id)
        {
            _database.Customers.RemoveAll(customer => customer.Id == id);

            if (_database.Customers.Count == 0)
            {
                Response.Headers.Add("HX-Refresh", "true");
            }

            return new OkResult();
        }

    }
}

Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace HtmxDemo.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace HtmxDemo.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

Pages/InfiniteScrolling.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HtmxDemo.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace HtmxDemo.Pages
{
    public class InfiniteScrolling : PageModel
    {
        private readonly Database _database;

        public List<Tweet> InitialTweets { get; set; }

        public InfiniteScrolling(Database database)
        {
            _database = database;
        }
        
        public void OnGet()
        {
            InitialTweets = _database.Tweets.OrderByDescending(t => t.Time).Take(20).ToList();
        }

        public async Task<IActionResult> OnGetLoadTweets(DateTime after)
        {
            var next20Tweets = _database.Tweets
                .OrderByDescending(t => t.Time)
                .Where(t => t.Time < after)
                .Take(20)
                .ToList();

            // Artificial delay to simulate it taking some time to load the next set of records
            // For goodness sake, don't add this to your production code :D
            await Task.Delay(2000);  
            
            return Partial("_TweetList", next20Tweets);
        }
    }
}

Pages/InlineEdit.cshtml.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using HtmxDemo.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace HtmxDemo.Pages
{
    // PLEASE NOTE: This is not production-ready code as I do not do any sort of error checking at any point
    public class InlineEditModel : PageModel
    {
        public class CustomerEditModel
        {
            [Required]
            public string FirstName { get; set; }

            [Required]
            public string LastName { get; set; }

            [Required]
            [EmailAddress]
            public string EmailAddress { get; set; }
        }
        
        private readonly Database _database;

        public List<Customer> Customers { get; set; }

        public InlineEditModel(Database database)
        {
            _database = database;
        }

        public void OnGet()
        {
            Customers = _database.Customers;
        }

        public IActionResult OnPostEdit(int id)
        {
            var customer = _database.Customers.First(c => c.Id == id);

            return Partial("_CustomerForm", customer);
        }

        public IActionResult OnPostUpdate(int id, [FromForm] CustomerEditModel model)
        {
            var customer = _database.Customers.First(c => c.Id == id);
            if (!ModelState.IsValid)
            {
                return Partial("_CustomerForm", customer); 
            }
            
            customer.FirstName = model.FirstName;
            customer.LastName = model.LastName;
            customer.EmailAddress = model.EmailAddress;

            return Partial("_CustomerDetail", customer);
        }

        public IActionResult OnGetCancel(int id)
        {
            var customer = _database.Customers.First(c => c.Id == id);

            return Partial("_CustomerDetail", customer);
        }
    }
}

Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace HtmxDemo.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Pages/DeleteItems.cshtml
@page
@model DeleteItemsModel
@{
    ViewData["Title"] = "Delete items";
}

<div class="container">
    <div class="row">
        <div class="col">
            <div class="card mt-5">
                <div class="card-header">
                    <div class="row align-items-center">
                        <div class="col">
                            <h4>
                                Customers
                            </h4>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <ul hx-boost="true"
                        hx-target="closest li"
                        hx-swap="outerHTML swap:1s"
                        hx-confirm="Are you sure you want to delete this customer?"
                        class="customer-list list-group list-group-lg list-group-flush list my--4">
                        @foreach (var customer in Model.Customers)
                        {
                            <li class="list-group-item px-0">
                                <div class="row align-items-center">
                                    <div class="col-auto">
                                        <span class="avatar avatar-lg">
                                            <img src="@customer.Avatar" alt="" class="avatar-img">
                                        </span>
                                    </div>
                                    <div class="col ml--2">
                                        <h4 class="card-title mb-1">
                                            @GetCustomerFullName(customer)
                                        </h4>
                                        <p class="card-text small text-muted mb-1">
                                            @customer.EmailAddress
                                        </p>
                                    </div>
                                    <div class="col-auto">
                                        <form asp-page-handler="Delete" asp-route-id="@customer.Id">
                                            <button type="submit" class="btn btn-sm btn-danger d-none d-md-inline-block">
                                                Delete
                                            </button>
                                        </form>
                                    </div>
                                </div>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

@section Head {
    <style>
        .customer-list li.htmx-swapping {
          opacity: 0;
          transition: opacity 1s ease-out;
        }
    </style>
}

@functions {

    string GetCustomerFullName(Customer customer)
    {
        return $"{customer.FirstName} {customer.LastName}";
    }

}

Pages/DeleteWithPartialRefresh.cshtml
@page
@model HtmxDemo.Pages.DeleteWithPartialRefreshModel
@{
    ViewData["Title"] = "Delete items";
}

<div class="container">
    <div class="row">
        <div class="col">
            <div class="card mt-5">
                <div class="card-header">
                    <div class="row align-items-center">
                        <div class="col">
                            <h4>
                                Customers
                            </h4>
                        </div>
                    </div>
                </div>
                <div hx-boost="true"
                     hx-target="this"
                     hx-swap="innerHTML"
                     hx-confirm="Are you sure you want to delete this customer?"
                     class="card-body">
                    <partial name="_CustomerList" model="Model.Customers"/>
                </div>
            </div>
        </div>
    </div>
</div>

Pages/DeleteWithRefresh.cshtml
@page
@model HtmxDemo.Pages.DeleteWithRefreshModel
@{
    ViewData["Title"] = "Delete items";
}

<div class="container">
    <div class="row">
        <div class="col">
            <div class="card mt-5">
                <div class="card-header">
                    <div class="row align-items-center">
                        <div class="col">
                            <h4>
                                Customers
                            </h4>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    @if (Model.Customers.Any())
                    {
                        <ul hx-boost="true"
                            hx-target="closest li"
                            hx-swap="outerHTML swap:1s"
                            hx-confirm="Are you sure you want to delete this customer?"
                            class="customer-list list-group list-group-lg list-group-flush list my--4">
                            @foreach (var customer in Model.Customers)
                            {
                                <li class="list-group-item px-0">
                                    <div class="row align-items-center">
                                        <div class="col-auto">
                                            <span class="avatar avatar-lg">
                                                <img src="@customer.Avatar" alt="" class="avatar-img">
                                            </span>
                                        </div>
                                        <div class="col ml--2">
                                            <h4 class="card-title mb-1">
                                                @GetCustomerFullName(customer)
                                            </h4>
                                            <p class="card-text small text-muted mb-1">
                                                @customer.EmailAddress
                                            </p>
                                        </div>
                                        <div class="col-auto">
                                            <form asp-page-handler="Delete" asp-route-id="@customer.Id">
                                                <button type="submit" class="btn btn-sm btn-danger d-none d-md-inline-block">
                                                    Delete
                                                </button>
                                            </form>
                                        </div>
                                    </div>
                                </li>
                            }
                        </ul>
                    }
                    else
                    {
                        <div class="row justify-content-center text-center">
                            <div class="col-12 col-md-10 mt-5">

                                <i class="fa fa-user fa-5x mb-5"></i>

                                <h2>
                                    No Customers
                                </h2>

                                <p class="text-muted">
                                    You do not have any customers yet. Add a new customer by clicking the <strong>Add Customer</strong> button below.
                                </p>

                                <a class="btn btn-lg btn-primary d-none d-md-inline-block mt-3" href="#">Add Customer</a>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

@section Head {
    <style>
        .customer-list li.htmx-swapping {
          opacity: 0;
          transition: opacity 1s ease-out;
        }
    </style>
}

@functions {

    string GetCustomerFullName(Customer customer)
    {
        return $"{customer.FirstName} {customer.LastName}";
    }

}

Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<h1 class="display-4">Welcome</h1>
<p>This application demonstrates various scenarios for using <a href="https://htmx.org/" target="_blank">HTMX</a> with ASP.NET Core Razor Pages</p>
<ul>
    <li><a asp-page="/DeleteItems">Delete items from a list</a></li>
    <li><a asp-page="/DeleteWithRefresh">Delete items from a list (with full page refresh)</a></li>
    <li><a asp-page="/DeleteWithPartialRefresh">Delete items from a list (with partial page refresh)</a></li>
    <li><a asp-page="/InlineEdit">Inline editing</a></li>
    <li><a asp-page="/InfiniteScrolling">Infinite Scrolling</a></li>
</ul>

Pages/InfiniteScrolling.cshtml
@page
@model InfiniteScrolling
@{
    ViewData["Title"] = "Infinite Scrolling";
}

<div class="container">
    <div class="row">
        <div class="col" hx-indicator="#loading-indicator">
            <h1 class="mb-5">
                Tweets
            </h1>
            <partial name="_TweetList" model="@Model.InitialTweets"/>
            <div id="loading-indicator" class="m-3">Loading more tweets...</div>
        </div>
    </div>
</div>

Pages/InlineEdit.cshtml
@page
@model InlineEditModel
@{
    ViewData["Title"] = "Inline editing";
}

<div class="container">
    <div class="row">
        <div class="col">
            <div class="card mt-5">
                <div class="card-header">
                    <div class="row align-items-center">
                        <div class="col">
                            <h4>
                                Customers
                            </h4>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                <ul hx-boost="true"
                    hx-target="closest li"
                    hx-swap="innerHTML"
                    class="customer-list list-group list-group-lg list-group-flush list my--4">
                        @foreach (var customer in Model.Customers)
                        {
                            <li class="list-group-item px-0">
                                <partial name="_CustomerDetail" model="customer"></partial>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HtmxDemo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    
    @await RenderSectionAsync("Head", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">HtmxDemo</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - HtmxDemo - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/htmx.org/dist/htmx.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Pages/_CustomerDetail.cshtml
@model Customer

<div class="row align-items-center">
    <div class="col-auto">
        <span class="avatar avatar-lg">
            <img src="@Model.Avatar" alt="" class="avatar-img">
        </span>
    </div>
    <div class="col ml--2">
        <h4 class="card-title mb-1">
            @GetCustomerFullName(Model)
        </h4>
        <p class="card-text small text-muted mb-1">
            @Model.EmailAddress
        </p>
    </div>
    <div class="col-auto">
        <form asp-page-handler="Edit" asp-route-id="@Model.Id">
            <button type="submit" class="btn btn-sm btn-primary d-none d-md-inline-block">
                Edit
            </button>
        </form>
    </div>
</div>

@functions {

    string GetCustomerFullName(Customer customer)
    {
        return $"{customer.FirstName} {customer.LastName}";
    }

}

Pages/_CustomerForm.cshtml
@model Customer

<form asp-page-handler="Update" asp-route-id="@Model.Id">
    <div class="form-row">
        <div class="form-group col-md-6">
            <label asp-for="FirstName"></label>
            <input asp-for="FirstName" type="text" class="form-control">
            <span asp-validation-for="FirstName" class="text-danger"></span>
        </div>
        <div class="form-group col-md-6">
            <label asp-for="LastName"></label>
            <input asp-for="LastName" type="text" class="form-control">
            <span asp-validation-for="LastName" class="text-danger"></span>
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-6">
            <label asp-for="EmailAddress"></label>
            <input asp-for="EmailAddress" type="text" class="form-control">
            <span asp-validation-for="EmailAddress" class="text-danger"></span>
        </div>
    </div>
    <a href="#" hx-get="@Url.Page("", "Cancel", new {id = Model.Id})" class="btn btn-sm btn-secondary d-none d-md-inline-block">
        Cancel Changes
    </a>
    <button class="btn btn-sm btn-primary d-none d-md-inline-block">
        Save Changes
    </button>
</form>

Pages/_CustomerList.cshtml
@model IEnumerable<Customer>

@if (Model.Any())
{
    <ul class="customer-list list-group list-group-lg list-group-flush list my--4">
        @foreach (var customer in Model)
        {
            <li class="list-group-item px-0">
                <div class="row align-items-center">
                    <div class="col-auto">
                        <span class="avatar avatar-lg">
                            <img src="@customer.Avatar" alt="" class="avatar-img">
                        </span>
                    </div>
                    <div class="col ml--2">
                        <h4 class="card-title mb-1">
                            @GetCustomerFullName(customer)
                        </h4>
                        <p class="card-text small text-muted mb-1">
                            @customer.EmailAddress
                        </p>
                    </div>
                    <div class="col-auto">
                        <form asp-page-handler="Delete" asp-route-id="@customer.Id">
                            <button type="submit" class="btn btn-sm btn-danger d-none d-md-inline-block">
                                Delete
                            </button>
                        </form>
                    </div>
                </div>
            </li>
        }
    </ul>
}
else
{
    <div class="row justify-content-center text-center">
        <div class="col-12 col-md-10 mt-5">

            <i class="fa fa-user fa-5x mb-5"></i>

            <h2>
                No Customers
            </h2>

            <p class="text-muted">
                You do not have any customers yet. Add a new customer by clicking the <strong>Add Customer</strong> button below.
            </p>

            <a class="btn btn-lg btn-primary d-none d-md-inline-block mt-3" href="#">Add Customer</a>
        </div>
    </div>
}

@functions {

    string GetCustomerFullName(Customer customer)
    {
        return $"{customer.FirstName} {customer.LastName}";
    }

}

Pages/_TweetList.cshtml
@model IEnumerable<Tweet>

@if (Model.Any())
{
    @foreach (var tweet in Model)
    {
        <div class="media mb-2">
            <img src="@tweet.Avatar" class="mr-3" alt="Avatar for @tweet.Username" style="width: 50px; height: 50px;">
            <div class="media-body">
                <p class="mb-1">
                    <strong>@tweet.Username</strong>
                </p>
                <p class="mb-1">@tweet.Text</p>
                <p class="small text-muted">@tweet.Time.ToString("f")</p>
            </div>
        </div>
    }
    <div
        hx-get="@Url.Page("", "LoadTweets", new {after = Model.Last().Time.ToString("O")})"
        hx-trigger="revealed"
        hx-swap="outerHTML">
    </div>
}
else
{
    <p class="text-center">No more tweets 😭</p>
}